BasedOnStyle: LLVM
ColumnLimit: 500
InsertBraces: true
AlignEscapedNewlines: DontAlign
AlignAfterOpenBracket: false
AlignArrayOfStructures: None
AlignConsecutiveAssignments: None
AlignConsecutiveBitFields: None
AlignConsecutiveDeclarations: None
AlignConsecutiveMacros: None
AlignOperands: false
AlignTrailingComments: false
